---
version: '2'
services:
  web:
    build: .
    ports:
      - 80:4000
      - 443:4001
    labels:
      - convox.port.443.protocol=tls
      - convox.port.443.proxy=true
      - convox.health.timeout=60
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
      - CONVOX_HOST
      - CONVOX_PASSWORD
    depends_on:
      - redis
      - database
    links:
      - database
      - redis
    command: ./bin/web
  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    links:
      - database
      - redis
    build: .
    environment:
      - RAILS_ENV=development
      - CONVOX_HOST
      - CONVOX_PASSWORD
    command: sidekiq
    #command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '/usr/src/terminus'
    env_file:
      - '.env'

  database:
    image: convox/postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5434:5432
  redis:
    image: convox/redis
    ports:
      - 6379
