---
version: '2'
services:
  web:
    build: .
    ports:
      - 80:4000
      - 443:4001
    labels:
      - convox.port.443.protocol=tls
      - convox.port.443.proxy=true
      - convox.health.timeout=60
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
    links:
      - database
  database:
    image: convox/postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5433:5432
