version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: echo "hello world"
      - deploy:
        name: "Convox Deploy"
        command
      - convox login console.convox.com
      - convox switch org/rack
      - convox deploy --app app
      - convox run web rake db:migrate --app app

