version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: echo "hello world"
      - deploy:
        name: "Convox Deploy"
        commands:
          - convox login console.convox.com
          - convox switch personal/staging4
          - convox deploy --app hound
          - convox run web rake db:migrate --app hound

